import { spawnSync } from 'node:child_process';
import { cp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { basename, dirname, join, resolve } from 'node:path';

const [, , command, ...args] = process.argv;
const PLUGIN_PYTHON_ROOT = resolve(process.cwd(), 'src-tauri', 'resources', 'plugin-python');
const EMBEDDED_PYTHON = resolve(PLUGIN_PYTHON_ROOT, 'windows-x64', 'python.exe');
const GET_PIP_PATH = resolve(PLUGIN_PYTHON_ROOT, 'get-pip.py');

function usage() {
  console.log(`Usage:
  node scripts/plugin-tool.mjs init <targetDir> [pluginId]
  node scripts/plugin-tool.mjs validate <pluginDir>
  node scripts/plugin-tool.mjs pack <pluginDir> [outputDir]`);
}

async function ensureDir(targetPath) {
  await mkdir(targetPath, { recursive: true });
}

async function writeJson(targetPath, value) {
  await writeFile(targetPath, `${JSON.stringify(value, null, 2)}\n`);
}

function ensureEmbeddedPython() {
  if (!existsSync(EMBEDDED_PYTHON)) {
    throw new Error('embedded plugin python is missing. Run `npm run prepare:plugin-python` first.');
  }

  return EMBEDDED_PYTHON;
}

async function ensureEmbeddedPythonLayout(python) {
  const runtimeDir = dirname(python);
  await ensureDir(join(runtimeDir, 'Lib', 'site-packages'));
  return runtimeDir;
}

function buildEmbeddedPythonEnv(runtimeDir, extraPythonPathEntries = []) {
  return {
    ...process.env,
    PYTHONHOME: runtimeDir,
    PYTHONPATH: extraPythonPathEntries.join(process.platform === 'win32' ? ';' : ':'),
    PYTHONNOUSERSITE: '1',
    PYTHONIOENCODING: 'utf-8',
    PYTHONUTF8: '1',
  };
}

async function ensurePipAvailable(python) {
  const runtimeDir = await ensureEmbeddedPythonLayout(python);
  const env = buildEmbeddedPythonEnv(runtimeDir);
  const pipVersion = spawnSync(python, ['-m', 'pip', '--version'], {
    stdio: 'ignore',
    cwd: process.cwd(),
    env,
  });
  if (pipVersion.status === 0) {
    return;
  }

  if (!existsSync(GET_PIP_PATH)) {
    throw new Error('get-pip.py is missing. Run `npm run prepare:plugin-python` first.');
  }

  const bootstrap = spawnSync(python, [GET_PIP_PATH, '--no-warn-script-location'], {
    stdio: 'inherit',
    cwd: process.cwd(),
    env,
  });
  if (bootstrap.status !== 0) {
    throw new Error(`failed to bootstrap pip for embedded plugin python (exit code ${bootstrap.status ?? 'unknown'})`);
  }

  const verify = spawnSync(python, ['-m', 'pip', '--version'], {
    stdio: 'ignore',
    cwd: process.cwd(),
    env,
  });
  if (verify.status !== 0) {
    throw new Error('embedded plugin python pip verification failed');
  }
}

async function initPlugin(targetDir, pluginIdArg) {
  const pluginDir = resolve(process.cwd(), targetDir);
  const pluginId = (pluginIdArg || basename(pluginDir)).trim();
  const manifest = {
    id: pluginId,
    name: pluginId,
    version: '0.1.0',
    apiVersion: '1',
    runtime: 'python',
    entry: 'main.py',
    description: 'PM Center plugin',
    enabledByDefault: true,
    contributes: {
      commands: [
        {
          id: 'hello',
          title: 'Hello Plugin',
          description: 'Example toolbar action',
        },
      ],
      toolbarActions: [
        {
          command: 'hello',
          when: {
            projectOpen: true,
          },
        },
      ],
      fileContextActions: [
        {
          command: 'hello',
          when: {
            selectionCount: 'single',
            targetKind: 'file',
          },
        },
      ],
    },
    permissions: [],
  };

  const mainPy = `from pmc_plugin import run, toast, result


def handle(request):
    selected = request.get("selectedItems", [])
    count = len(selected)
    toast(f"Plugin triggered with {count} selected item(s)", title="Hello Plugin", tone="success")
    print("progress /***100*/", flush=True)
    result({"selectedCount": count})


if __name__ == "__main__":
    run(handle)
`;

  await ensureDir(pluginDir);
  await writeJson(join(pluginDir, 'plugin.json'), manifest);
  await writeFile(join(pluginDir, 'main.py'), mainPy);
  await writeFile(join(pluginDir, 'requirements.txt'), '');
  await writeFile(join(pluginDir, 'README.md'), `# ${pluginId}\n\nGenerated by plugin-tool.\n`);
  console.log(`[plugin-tool] initialized ${pluginDir}`);
}

async function loadManifest(pluginDir) {
  const manifestPath = join(pluginDir, 'plugin.json');
  const raw = await readFile(manifestPath, 'utf8');
  return JSON.parse(raw);
}

function validateManifest(manifest) {
  const issues = [];

  for (const field of ['id', 'name', 'version', 'apiVersion', 'runtime', 'entry']) {
    if (!manifest[field] || typeof manifest[field] !== 'string') {
      issues.push(`missing or invalid ${field}`);
    }
  }

  if (manifest.runtime && manifest.runtime !== 'python') {
    issues.push('runtime must be "python" for v1');
  }

  const commands = new Set();
  for (const command of manifest.contributes?.commands || []) {
    if (!command.id) {
      issues.push('command is missing id');
      continue;
    }
    if (commands.has(command.id)) {
      issues.push(`duplicate command id: ${command.id}`);
    }
    commands.add(command.id);
  }

  for (const groupName of ['toolbarActions', 'fileContextActions']) {
    for (const action of manifest.contributes?.[groupName] || []) {
      if (!action.command || !commands.has(action.command)) {
        issues.push(`${groupName} references missing command: ${action.command || '(empty)'}`);
      }

      if (groupName !== 'fileContextActions' || !action.menu) {
        continue;
      }

      const placement = (action.menu.placement || 'section').trim().toLowerCase();
      if (placement !== 'section' && placement !== 'inline') {
        issues.push(`fileContextActions menu.placement must be "section" or "inline": ${action.command}`);
      }

      if (action.menu.submenu !== undefined) {
        if (typeof action.menu.submenu !== 'string' || action.menu.submenu.trim() === '') {
          issues.push(`fileContextActions menu.submenu must be a non-empty string: ${action.command}`);
        }
      }
    }
  }

  return issues;
}

async function validatePlugin(pluginDirArg) {
  const pluginDir = resolve(process.cwd(), pluginDirArg);
  const manifest = await loadManifest(pluginDir);
  const issues = validateManifest(manifest);
  const entryPath = join(pluginDir, manifest.entry || 'main.py');

  if (!existsSync(entryPath)) {
    issues.push(`entry file does not exist: ${entryPath}`);
  }

  if (issues.length > 0) {
    console.error('[plugin-tool] validation failed:');
    for (const issue of issues) {
      console.error(`  - ${issue}`);
    }
    process.exitCode = 1;
    return;
  }

  console.log(`[plugin-tool] validation ok: ${pluginDir}`);
}

async function copyPluginFiles(sourceDir, destinationDir) {
  await rm(destinationDir, { recursive: true, force: true });
  await ensureDir(destinationDir);

  const entries = await readdir(sourceDir, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.name === 'vendor' || entry.name === '__pycache__' || entry.name === '.git') {
      continue;
    }

    await cp(join(sourceDir, entry.name), join(destinationDir, entry.name), {
      recursive: true,
      force: true,
    });
  }
}

async function packPlugin(pluginDirArg, outputDirArg) {
  const pluginDir = resolve(process.cwd(), pluginDirArg);
  const manifest = await loadManifest(pluginDir);
  const issues = validateManifest(manifest);
  if (issues.length > 0) {
    console.error('[plugin-tool] pack aborted: plugin is invalid');
    for (const issue of issues) {
      console.error(`  - ${issue}`);
    }
    process.exit(1);
  }

  const outputRoot = resolve(process.cwd(), outputDirArg || 'dist/plugin-packages');
  const destinationDir = join(outputRoot, manifest.id);
  await ensureDir(outputRoot);
  await copyPluginFiles(pluginDir, destinationDir);

  const requirementsPath = join(pluginDir, 'requirements.txt');
  if (existsSync(requirementsPath)) {
    const requirements = (await readFile(requirementsPath, 'utf8')).trim();
    if (requirements) {
      const python = ensureEmbeddedPython();
      await ensurePipAvailable(python);
      const runtimeDir = await ensureEmbeddedPythonLayout(python);

      const vendorDir = join(destinationDir, 'vendor');
      await rm(vendorDir, { recursive: true, force: true });
      await ensureDir(vendorDir);

      const result = spawnSync(
        python,
        [
          '-m',
          'pip',
          'install',
          '--disable-pip-version-check',
          '--upgrade',
          '-r',
          requirementsPath,
          '--target',
          vendorDir,
          '--no-compile',
        ],
        {
          stdio: 'inherit',
          cwd: pluginDir,
          env: buildEmbeddedPythonEnv(runtimeDir),
        },
      );

      if (result.status !== 0) {
        throw new Error('pip install for plugin vendor failed');
      }
    }
  }

  console.log(`[plugin-tool] packed ${manifest.id} -> ${destinationDir}`);
}

async function main() {
  if (!command) {
    usage();
    process.exit(1);
  }

  if (command === 'init') {
    const [targetDir, pluginId] = args;
    if (!targetDir) {
      usage();
      process.exit(1);
    }
    await initPlugin(targetDir, pluginId);
    return;
  }

  if (command === 'validate') {
    const [pluginDir] = args;
    if (!pluginDir) {
      usage();
      process.exit(1);
    }
    await validatePlugin(pluginDir);
    return;
  }

  if (command === 'pack') {
    const [pluginDir, outputDir] = args;
    if (!pluginDir) {
      usage();
      process.exit(1);
    }
    await packPlugin(pluginDir, outputDir);
    return;
  }

  usage();
  process.exit(1);
}

main().catch((error) => {
  console.error('[plugin-tool] failed:', error);
  process.exit(1);
});
